tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "emanuelcasco/tap"
tap "homebrew/cask-fonts"

brew "atuin"
brew "bat"
brew "fd"
brew "fzf"
brew "ghq"
brew "git"
brew "herdr"
brew "jq"
brew "mas"
brew "mise"
brew "ocgo"
brew "opencode"
brew "rg"
brew "tmux"
brew "vim"
brew "zoxide"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "1password"
cask "1password-cli"
cask "bettertouchtool"
cask "claude-code"
cask "discord"
cask "docker"
cask "font-hack-nerd-font"
cask "font-hackgen-nerd"
cask "ghostty"
cask "google-chrome"
cask "karabiner-elements"
cask "raycast"
cask "visual-studio-code"

mas "BetterSnapTool", id: 417375580
