tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "emanuelcasco/tap"

brew "git"
brew "mas"
brew "ocgo"
brew "tmux"
brew "vim"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "1password"
cask "1password-cli"
cask "bettertouchtool"
cask "discord"
cask "docker"
cask "google-chrome"
cask "karabiner-elements"
cask "raycast"
cask "visual-studio-code"

mas "BetterSnapTool", id: 417375580
