[tools]
yarn = "latest"
go = "latest"
"go:github.com/rhysd/vim-startuptime" = "latest"
neovim = "latest"
deno = "latest"
ripgrep = "latest"
zoxide = "latest"
ghq = "latest"
fzf = "latest"
lazygit = "latest"
delta = "latest"
gitui = "latest"
yazi = "latest"
node = "latest"
lua-language-server = "latest"
fd = "latest"
github-cli = "latest"
"npm:typescript-language-server" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
tmux = "latest"
ffmpeg = "latest"
pnpm = "latest"
rust = "latest"
"cargo:create-tauri-app" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@github/copilot-language-server" = "latest"

[settings]
experimental = true
