[tools]
yarn = "latest"
go = "latest"
"go:github.com/rhysd/vim-startuptime" = "latest"
neovim = "latest"
deno = "latest"
ripgrep = "latest"
zoxide = "latest"
ghq = "latest"
fzf = "latest"
lazygit = "latest"
delta = "latest"
gitui = "latest"
yazi = "latest"
node = "latest"
bun = "latest"
lua-language-server = "latest"
fd = "latest"
github-cli = "latest"
"ubi:babarot/gomi" = "latest"
"go:github.com/babarot/gomi" = "latest"
"npm:typescript-language-server" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
tmux = "latest"
ffmpeg = "latest"

[settings]
experimental = true
