return {}
-- return {
--   {
--     'https://github.com/adelarsq/image_preview.nvim',
--     ft = 'markdown',
--   },
--   {
--     'https://github.com/cohama/lexima.vim',
--     event = { 'CmdlineEnter', 'InsertEnter' },
--     lazy = true,
--     config = function()
--       vim.g.lexima_enable_space_rules = 0
--     end,
--   },
--   {
--     'https://github.com/thinca/vim-qfreplace',
--     event = { 'CmdlineEnter' },
--   },
--   {
--     'https://github.com/yuki-yano/lexima-alter-command.vim',
--     dependencies = {
--       'https://github.com/cohama/lexima.vim'
--     },
--     event = { 'CmdlineEnter' },
--     config = function()
--       vim.cmd [[
--       LeximaAlterCommand obw ObsidianWorkspace
--       LeximaAlterCommand obd ObsidianDailies
--       LeximaAlterCommand obt ObsidianToday
--       LeximaAlterCommand obe ObsidianExtractNote
--       ]]
--     end,
--   },
--   {
--     'https://github.com/machakann/vim-sandwich',
--   },
--   {
--     'https://github.com/monaqa/dial.nvim',
--     keys = { "<C-a>", "<C-x>", "g<C-a>", "g<C-x>" },
--     config = function()
--       local augend = require("dial.augend")
--       require("dial.config").augends:register_group({
--         default = {
--           augend.integer.alias.decimal, -- 整数（10進数）の増減
--           augend.integer.alias.hex,     -- 整数（16進数）の増減
--           augend.date.alias["%Y/%m/%d"], -- 日付の増減
--           augend.constant.alias.bool,  -- true/false のトグル
--         },
--       })
-- 
--       vim.keymap.set("n", "<C-a>", require("dial.map").inc_normal(), { noremap = true })
--       vim.keymap.set("n", "<C-x>", require("dial.map").dec_normal(), { noremap = true })
--       vim.keymap.set("v", "<C-a>", require("dial.map").inc_visual(), { noremap = true })
--       vim.keymap.set("v", "<C-x>", require("dial.map").dec_visual(), { noremap = true })
--       vim.keymap.set("v", "g<C-a>", require("dial.map").inc_gvisual(), { noremap = true })
--       vim.keymap.set("v", "g<C-x>", require("dial.map").dec_gvisual(), { noremap = true })
--     end,
--   }
-- }
