PROMPT='%n$'

source ~/.zplug/init.zsh

# Set the priority when loading
# e.g., zsh-syntax-highlighting must be loaded
# after executing compinit command and sourcing other plugins
zplug "zsh-users/zsh-syntax-highlighting", nice:10

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load --verbose

# auto complete on
autoload -U compinit; compinit

# stack on directory stack when cd
setopt auto_pushd

#########################
# alias
#########################
alias la="ls -Al"
alias hm="cd ~/src/github.com/tkancf"
alias v="nvim"
alias t="tmux"
alias ta="tmux a"
alias tk="tmux kill-server"
alias g="git"

#########################
# pecol function
#########################
function peco-src () {
  local selected_dir=$(ghq list -p | peco --query "$LBUFFER")
  if [ -n "$selected_dir" ]; then
    BUFFER="cd ${selected_dir}"
    zle accept-line
  fi
  zle clear-screen
}
zle -N peco-src
bindkey '^]' peco-src

