[tools]
go = "latest"
node = "latest"
bun = "latest"
lua-language-server = "latest"
"npm:typescript-language-server" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"terraform-ls" = "latest"
"npm:ansible-language-server" = "latest"
rust = "latest"
python = "latest"
"npm:@openai/codex" = "latest"
"asdf:neovim" = "nightly"
"npm:pyright" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
